insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Cile', 'Brazil', 2, 3, 3, 1, 'Estadio das Dunas, Natal', '2014-06-27 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Urugvaj', 'Kolumbija', 0, 2, 5, 1, 'Arena Fonte Nova, Salvador', '2014-06-27 10:12:50')
go

insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Meksiko', 'Holandija', 1, 2, 4, 0, 'Arena da Baixada, Curitiba', '2014-06-28 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Grcka', 'Kostarika', 3, 5, 4, 2, 'Arena da Baixada, Curitiba', '2014-06-28 10:12:50')
go

insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Nigerija', 'Francuska', 0, 2, 4, 0, 'Arena da Baixada, Curitiba', '2014-06-29 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Alzir', 'Nemacka', 1, 2, 4, 2, 'Arena da Baixada, Curitiba', '2014-06-29 10:12:50')
go

insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Svajcarska', 'Argentina', 0, 1, 4, 0, 'Arena da Baixada, Curitiba', '2014-06-29 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Amerika', 'Belgija', 1, 2, 4, 2, 'Arena da Baixada, Curitiba', '2014-06-29 10:12:50')
go

insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Nemacka', 'Francuska', 1, 2, 4, 2, 'Arena da Baixada, Curitiba', '2014-07-04 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Kolumbija', 'Brazil', 0, 3, 4, 0, 'Estadio das Dunas, Natal', '2014-07-04 10:12:50')
go

insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Belgija', 'Argentina', 0, 1, 4, 2, 'Arena da Baixada, Curitiba', '2014-07-05 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Kostarika', 'Holandija', 1, 3, 4, 0, 'Estadio das Dunas, Natal', '2014-07-05 10:12:50')
go

insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Brazil', 'Nemacka', 2, 1, 4, 2, 'Arena da Baixada, Curitiba', '2014-07-05 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Belgija', 'Holandija', 1, 0, 4, 0, 'Estadio das Dunas, Natal', '2014-07-05 10:12:50')
go

insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Brazil', 'Belgija', 3, 0, 4, 0, 'Estadio das Dunas, Natal', '2014-07-05 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Holandija', 'Nemacka', 0, 2, 4, 0, 'Estadio das Dunas, Natal', '2014-07-05 10:12:50')
go