insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Brazil', '1930-12-15 00:00:00', 'Prvo mesto', 20)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Meksiko', '1930-12-15 00:00:00', 'Cetvrtfinale', 15)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Hrvatska', '1998-12-15 00:00:00', 'Polufinale', 4)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Kamerun', '1982-12-15 00:00:00', 'Cetvrtfinale', 7)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Holandija', '1934-12-15 00:00:00', 'Finale', 10)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Cile', '1930-12-15 00:00:00', 'Trece mesto', 9)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Spanija', '1934-12-15 00:00:00', 'Prvo mesto', 14)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Australija', '1974-12-15 00:00:00', 'Osmina finala', 4)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Kolumbija', '1962-12-15 00:00:00', 'Osmina finala', 5)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Grcka', '1994-12-15 00:00:00', 'Osmina finala', 3)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Obala slonovace', '2006-12-15 00:00:00', 'Prva runda', 3)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Japan', '1998-12-15 00:00:00', 'Osmina finala', 5)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Kostarika', '1990-12-15 00:00:00', 'Cetvrtfinale', 4)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Urugvaj', '1930-12-15 00:00:00', 'Prvo mesto', 11)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Italija', '1934-12-15 00:00:00', 'Prvo mesto', 17)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Engleska', '1950-12-15 00:00:00', 'Prvo mesto', 14)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Francuska', '1950-12-15 00:00:00', 'Prvo mesto', 14)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Svajcarska', '1934-12-15 00:00:00', 'Osmina finala', 9)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Ekvador', '1962-12-15 00:00:00', 'Grupna faza', 14)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Honduras', '1982-12-15 00:00:00', 'Grupna faza', 3)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Argentina', '1930-12-15 00:00:00', 'Prvo mesto', 14)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Nigerija', '1994-12-15 00:00:00', 'Osmina finala', 5)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Bosna i Hercegovina', '2014-12-15 00:00:00', 'Grupna faza', 1)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Iran', '1978-12-15 00:00:00', 'Prva runda', 4)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Nemacka', '1934-12-15 00:00:00', 'Prvo mesto', 17)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Amerika', '1930-12-15 00:00:00', 'Polufinale', 10)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Portugal', '1966-12-15 00:00:00', 'Polufinale', 6)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Gana', '2006-12-15 00:00:00', 'Cetvrtfinale', 2)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Belgija', '1930-12-15 00:00:00', 'Cetvrto mesto', 12)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Alzir', '1982-12-15 00:00:00', 'Osmina finala', 4)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Rusija', '1958-12-15 00:00:00', 'Cetvrto mesto', 10)
go
insert into TIM (NAZIV_TIMA, PRVI_PUT_IGRAO_NA_SP, NAJVECI_USPEH, BROJ_UCESCA) values ('Republika Koreja', '1954-12-15 00:00:00', 'Cetvrto mesto', 9)
go


insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Hrvatska', 'Brazil', 1, 3, 4, 0, 'Arena Corinthians, Sao Paulo', '2014-06-12 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Kamerun', 'Meksiko', 0, 1, 2, 0, 'Estadio das Dunas, Natal', '2014-06-13 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Holandija', 'Spanija', 1, 5, 4, 0, 'Arena Fonte Nova, Salvador', '2014-06-13 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Australija', 'Cile', 1, 3, 4, 0, 'Arena Pantanal, Cuiaba', '2014-06-13 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Grcka', 'Kolumbija', 0, 3, 3, 0, 'Estadio Mineirao, Belo Horizonte', '2014-06-14 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Kostarika', 'Urugvaj', 3, 1, 5, 0, 'Estadio Castelao, Fortaleza', '2014-06-14 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Italija', 'Engleska', 2, 1, 1, 0, 'Arena Amazonia, Manaus', '2014-06-14 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Japan', 'Obala slonovace', 1, 2, 4, 0, 'Arena Pernambuco, Recife', '2014-06-14 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Ekvador', 'Svajcarska', 1, 2, 2, 0, 'Estadio Nacional de Brasilia, Brasilia', '2014-06-15 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Bosna i Hercegovina', 'Argentina', 1, 2, 3, 0, 'Estadio Maracana, Rio de Janeiro', '2014-06-15 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Honduras', 'Francuska', 0, 3, 7, 1, 'Estadio Beira-Rio, Porto Alegre', '2014-06-15 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Portugal', 'Nemacka', 0, 4, 1, 1, 'Arena Fonte Nova, Salvador', '2014-06-16 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Nigerija', 'Iran', 0, 0, 1, 2, 'Arena da Baixada, Curitiba', '2014-06-16 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Amerika', 'Gana', 2, 1, 4, 1, 'Estadio das Dunas, Natal', '2014-06-16 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Alzir', 'Belgija', 1, 2, 5, 1, 'Arena Fonte Nova, Salvador', '2014-06-17 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Meksiko', 'Brazil', 0, 0, 1, 0, 'Arena da Baixada, Curitiba', '2014-06-17 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Republika Koreja', 'Rusija', 1, 1, 3, 1, 'Estadio das Dunas, Natal', '2014-06-17 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Holandija', 'Australija', 3, 2, 5, 1, 'Arena Fonte Nova, Salvador', '2014-06-18 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Cile', 'Spanija', 2, 0, 1, 0, 'Arena da Baixada, Curitiba', '2014-06-18 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Hrvatska', 'Kamerun', 4, 0, 3, 1, 'Estadio das Dunas, Natal', '2014-06-18 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Obala slonovace', 'Kolumbija', 1, 2, 5, 1, 'Arena Fonte Nova, Salvador', '2014-06-19 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Grcka', 'Japan', 0, 0, 1, 0, 'Arena da Baixada, Curitiba', '2014-06-19 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Engleska', 'Urugvaj', 1, 2, 3, 1, 'Estadio das Dunas, Natal', '2014-06-19 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Kostarika', 'Italija', 1, 0, 2, 1, 'Arena Fonte Nova, Salvador', '2014-06-20 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Francuska', 'Svajcarska', 5, 2, 3, 0, 'Arena da Baixada, Curitiba', '2014-06-20 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Ekvador', 'Honduras', 2, 1, 3, 1, 'Estadio das Dunas, Natal', '2014-06-20 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Iran', 'Argentina', 0, 1, 5, 1, 'Arena Fonte Nova, Salvador', '2014-06-21 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Bosna i Hercegovina', 'Nigerija', 0, 1, 4, 0, 'Arena da Baixada, Curitiba', '2014-06-21 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Gana', 'Nemacka', 2, 2, 3, 1, 'Estadio das Dunas, Natal', '2014-06-21 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Rusija', 'Belgija', 0, 1, 5, 1, 'Arena Fonte Nova, Salvador', '2014-06-22 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Alzir', 'Republika Koreja', 4, 2, 4, 0, 'Arena da Baixada, Curitiba', '2014-06-22 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Portugal', 'Amerika', 2, 2, 3, 1, 'Estadio das Dunas, Natal', '2014-06-22 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Spanija', 'Australija', 3, 0, 3, 1, 'Estadio das Dunas, Natal', '2014-06-23 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Cile', 'Holandija', 0, 2, 5, 1, 'Arena Fonte Nova, Salvador', '2014-06-23 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Brazil', 'Kamerun', 4, 1, 4, 0, 'Arena da Baixada, Curitiba', '2014-06-23 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Meksiko', 'Hrvatska', 3, 1, 3, 1, 'Arena da Baixada, Curitiba', '2014-06-23 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Engleska', 'Kostarika', 0, 0, 3, 1, 'Estadio das Dunas, Natal', '2014-06-24 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Urugvaj', 'Italija', 1, 0, 5, 1, 'Arena Fonte Nova, Salvador', '2014-06-24 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Obala slonovace', 'Grcka', 1, 2, 4, 0, 'Arena da Baixada, Curitiba', '2014-06-24 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Kolumbija', 'Japan', 4, 1, 3, 1, 'Arena da Baixada, Curitiba', '2014-06-24 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Argentina', 'Nigerija', 3, 2, 3, 1, 'Estadio das Dunas, Natal', '2014-06-25 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Iran', 'Bosna i Hercegovina', 1, 3, 5, 1, 'Arena Fonte Nova, Salvador', '2014-06-25 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Svajcarska', 'Honduras', 3, 0, 4, 0, 'Arena da Baixada, Curitiba', '2014-06-25 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Francuska', 'Ekvador', 0, 0, 3, 1, 'Arena da Baixada, Curitiba', '2014-06-25 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Nemacka', 'Amerika', 1, 0, 3, 1, 'Estadio das Dunas, Natal', '2014-06-25 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Gana', 'Portugal', 1, 2, 5, 1, 'Arena Fonte Nova, Salvador', '2014-06-25 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Rusija', 'Alzir', 1, 1, 4, 0, 'Arena da Baixada, Curitiba', '2014-06-25 10:12:50')
go
insert into UTAKMICE (NAZIV_TIMA_GOSTI, NAZIV_TIMA_DOMACI, GOL_GOSTI, GOL_DOMACINI, BROJ_ZUTIH_KARTONA, BROJ_CRVENIH_KARTONA, STADION, DATUM_VREME) values ('Belgija', 'Republika Koreja', 1, 0, 3, 1, 'Arena da Baixada, Curitiba', '2014-06-25 10:12:50')
go

